apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctscapp-deployment
  labels:
    app: ctscapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctscapp
  template:
    metadata:
      labels:
        app: ctscapp 
    spec:
      containers:
      - name: ctscappserver
        image: ctscsliitjanaka/ctscapp:latest
        ports:
        - containerPort: 3000
