apiVersion: v1
kind: Service
metadata:
  name: ctscapp-service
spec:
  selector:
    app: ctscapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110
